# Generated by Django 4.0.4 on 2022-08-31 17:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cars', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('street_no', models.CharField(max_length=32)),
                ('floor', models.CharField(max_length=64)),
                ('flat', models.CharField(max_length=64)),
                ('directions', models.CharField(max_length=64)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.location')),
            ],
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign_start_day', models.DateTimeField()),
                ('campaign_end_day', models.DateTimeField()),
                ('campaign_code', models.CharField(max_length=16)),
                ('campaign_info', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=64, verbose_name='İsim Soyisim')),
                ('photo', models.ImageField(blank=True, null=True, upload_to=None, verbose_name='A photo of car')),
                ('phone_number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=128)),
                ('approved', models.BooleanField(default=False)),
                ('active_user', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('information', models.CharField(max_length=64, verbose_name='Kart Bilgileri')),
                ('name', models.CharField(max_length=64, verbose_name='İsim')),
                ('owner_name', models.CharField(max_length=64, verbose_name='Sahibin İsim')),
                ('number', models.IntegerField(default=0, verbose_name='Kart No')),
                ('csv', models.IntegerField(default=0, verbose_name='Kart No')),
                ('last_month', models.IntegerField(default=0, verbose_name='geçerli son ay')),
                ('last_year', models.IntegerField(default=0, verbose_name='geçerli son yıl')),
            ],
        ),
        migrations.CreateModel(
            name='Penalty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('penalty_price', models.IntegerField(default=0)),
                ('penalty_info', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='PlateLicence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=128, verbose_name='İsim Soyisim')),
                ('place', models.CharField(max_length=128, verbose_name='Verilme yeri')),
                ('document_no', models.IntegerField(default=0, verbose_name='Belge No')),
                ('date', models.DateTimeField(verbose_name='İlk belge tarihi')),
                ('candidate', models.BooleanField(default=False, verbose_name='Aday Sürücü')),
                ('serial_no', models.CharField(max_length=64, verbose_name='Seri Numarası')),
                ('licence_type', models.CharField(max_length=16, verbose_name='Ehliyet Sınıfı')),
            ],
        ),
        migrations.CreateModel(
            name='Journey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.FloatField(default=0.0)),
                ('total_minute', models.IntegerField(default=0)),
                ('total_distance', models.IntegerField(default=0)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(auto_now=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cars.car')),
                ('end_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='end_location', to='cars.location')),
                ('start_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='start_location', to='cars.location')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.customer')),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='cars',
            field=models.ManyToManyField(through='accounts.Journey', to='cars.car'),
        ),
        migrations.AddField(
            model_name='customer',
            name='full_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.address'),
        ),
        migrations.AddField(
            model_name='customer',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cars.location'),
        ),
        migrations.AddField(
            model_name='customer',
            name='payment_method',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.paymentmethod'),
        ),
        migrations.AddField(
            model_name='customer',
            name='plate_licence',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.platelicence'),
        ),
        migrations.AddField(
            model_name='customer',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='BlackListMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=128)),
                ('plate_licence', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.platelicence')),
            ],
        ),
    ]
