# Generated by Django 4.0.4 on 2022-08-31 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_text', models.CharField(max_length=256, verbose_name='Full Location')),
                ('latitude', models.FloatField(default=0.0)),
                ('longitude', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='Pricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minute', models.FloatField(default=0)),
                ('hourly', models.FloatField(default=0)),
                ('daily', models.FloatField(default=0)),
                ('extra_kilometer', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(null=True, upload_to=None, verbose_name='A photo of car')),
                ('brand', models.CharField(max_length=32, verbose_name='Brand')),
                ('model', models.CharField(max_length=128, verbose_name='Model')),
                ('segment', models.CharField(max_length=128, verbose_name='Segment')),
                ('year', models.DateTimeField(null=True, verbose_name='The year car build')),
                ('join_year', models.DateTimeField(auto_now_add=True, verbose_name='When the car is added to the system')),
                ('current_fuel_quantity', models.IntegerField(default=0, verbose_name='Current fuel quantity')),
                ('total_km', models.IntegerField(default=0)),
                ('total_fuel_quantity', models.IntegerField(default=0, verbose_name='Total fuel quantity')),
                ('body', models.CharField(default='', max_length=16)),
                ('fuel_type', models.CharField(default='Gasoline', max_length=64, verbose_name='Fuel type')),
                ('active', models.BooleanField(default=False, verbose_name='Active')),
                ('passenger_capacity', models.IntegerField(default=1, verbose_name='Passenger Capacity')),
                ('gear_type', models.CharField(max_length=32)),
                ('licence', models.CharField(default='', max_length=32, verbose_name='Licence')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cars.location')),
                ('price', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cars.pricing')),
            ],
            options={
                'ordering': ['join_year'],
            },
        ),
    ]
